### ISSUE TITLE
Error in command ?

### ISSUE THREAD

**Issue by stephgeoff** [xtacocorex/chip_batt_autoshutdown#2]
Hi, im a beggining Linux user, i highly suspect a 18 inch code there.. and i try to acheive this:

git clone https://github.com/xtacocorex/chip_batt_autoshutdown.git
  cd chip_batt_autoshutdown
  chmod +x chip_batt_autoshutdown.sh
  sudo cp ./chip_autoshutdown.sh /usr/bin/

1- I install git
2- I get to github : git clone https://github.com/xtacocorex/chip_batt_autoshutdown.git
3- I change the directory, using : cd chip_batt_autoshutdown
4- And there is the problem: 
root@chip:~/chip_batt_autoshutdown# chmod +x chip_batt_autoshutdown.sh
chmod: cannot access 'chip_batt_autoshutdown.sh': No such file or directory

I try this:
root@chip:~/chip_batt_autoshutdown# chmod +x chip_autoshutdown.sh
root@chip:~/chip_batt_autoshutdown# cp ./chip_autoshutdown.sh /usr/bin/
root@chip:~/chip_batt_autoshutdown# cd

And get this: 
root@chip:~#  battery.sh
BAT_STATUS=0
CHARG_IND=0
BAT_EXIST=1
CHARGE_CTL=0xc9
CHARGE_CTL2=0x45
Battery voltage = 4170.1mV
Battery discharge current = 0mA
Battery charge current = 0mA
Internal temperature = 40.1c
root@chip:~# 

Its normal to have nothing show in 
Battery discharge current = 0mA
Battery charge current = 0mA

Maybe i miss something?

**Comment by xtacocorex** [comment]
I swore I fixed the issue in the usage displayed in the README.  Will get that updated as soon as I can as you aren't the first to complain about that.

I seem to recall there being an issue with the stock battery.sh script that NTC provides.  What version of the OS are you running?

You definitely have a battery attached.  What happens if you run chip_autoshutdown.sh?  It should report that you have enough battery with the output of "CHIP BATTERY LEVEL IS GOOD".

**Comment by yratof** [comment]
Just to point out that 
`chmod +x chip_batt_autoshutdown.sh`
should be 
`chmod +x chip_autoshutdown.sh`

**Comment by xtacocorex** [comment]
just fixed the readme, closing.
